name: Generate Podcast Episode

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL of the article to turn into a podcast episode"
        required: true
        type: string

permissions:
  contents: write
  models: read

jobs:
  generate-episode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code branch
        uses: actions/checkout@v6.0.3
        with:
          path: main

      - name: Checkout episodes branch
        uses: actions/checkout@v6.0.3
        with:
          ref: episodes
          path: episodes
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "main/.python-version"
      - name: Install dependencies
        working-directory: main
        run: |
          uv sync
      - name: Generate BAML code
        working-directory: main
        run: |
          uv run baml generate --from baml_src/
      - name: Extract article
        working-directory: main
        run: |
          uv run trafilatura -u "${{ inputs.url }}" --with-metadata --output-format "json" > $RUNNER_TEMP/article.json
      - name: Generate episode details
        working-directory: main
        run: |
          uv run articlepod episode generate-meta $RUNNER_TEMP/article.json "${{ secrets.R2_BUCKET }}.r2.cloudflarestorage.com" > $RUNNER_TEMP/episode.json
      - name: Generate slug
        id: slug
        run: |
          slug=$(jq -r '.slug' $RUNNER_TEMP/episode.json)
          echo "slug=$slug" >> $GITHUB_OUTPUT
      - name: Generate podcast script
        working-directory: main
        run: |
          uv run articlepod episode generate-script $RUNNER_TEMP/article.json > $RUNNER_TEMP/script.txt
      - name: Upload script
        uses: actions/upload-artifact@v7
        with:
          name: script
          path: |
            $RUNNER_TEMP/episode.json
            $RUNNER_TEMP/script.txt
      - name: Generate audio
        working-directory: main
        run: |
          uv run edge-tts --file $RUNNER_TEMP/script.txt --output $RUNNER_TEMP/${{ steps.slug.outputs.slug }}.mp3
      - name: Upload compact database to R2
        uses: cloudflare/wrangler-action@v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4"
          command: |
            r2 object put --remote "${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}/${{ steps.slug.outputs.slug }}.mp3" --file $RUNNER_TEMP/${{ steps.slug.outputs.slug }}.mp3

      - name: Commit episode
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cp $RUNNER_TEMP/episode.json episodes/${{ steps.slug.outputs.slug }}.json
          git add episodes/${{ steps.slug.outputs.slug }}.json
          git commit -m "Add episode ${{ steps.slug.outputs.slug }}"
          git push origin episodes
