name: Add Article

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL of the article to turn into a podcast episode"
        required: true
        type: string

permissions:
  contents: write
  models: read

jobs:
  generate-episode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code branch
        uses: actions/checkout@v6.0.3
        with:
          path: main

      - name: Checkout episodes branch
        uses: actions/checkout@v6.0.3
        with:
          ref: episodes
          path: episodes
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "main/.python-version"
      - name: Install dependencies
        working-directory: main
        run: |
          uv sync
      - name: Generate BAML code
        working-directory: main
        run: |
          uv run baml generate --from baml_src/
      - name: Create temporary directory for articlepod data
        run: |
          mkdir -p $RUNNER_TEMP/articlepod-data
      - name: Extract article
        working-directory: main
        run: |
          uv run trafilatura -u "${{ inputs.url }}" --with-metadata --output-format "json" > $RUNNER_TEMP/articlepod-data/article.json
      - name: Generate episode details
        working-directory: main
        run: |
          uv run articlepod episode generate-meta $RUNNER_TEMP/articlepod-data/article.json "${{ secrets.CLOUDFLARE_R2_PUBLIC_URL }}" > $RUNNER_TEMP/articlepod-data/episode.json
      - name: Get metadata
        id: metadata
        run: |
          slug=$(jq -r '.slug' $RUNNER_TEMP/articlepod-data/episode.json)
          echo "slug=$slug" >> $GITHUB_OUTPUT
          title=$(jq -r '.title' $RUNNER_TEMP/articlepod-data/episode.json)
          echo "title=$title" >> $GITHUB_OUTPUT
      - name: Generate podcast script
        working-directory: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BAML_LOG: off
        run: |
          uv run articlepod episode generate-script $RUNNER_TEMP/articlepod-data/article.json > $RUNNER_TEMP/articlepod-data/script.txt
      - name: Upload script
        uses: actions/upload-artifact@v7
        with:
          name: script
          path: ${{ runner.temp }}/articlepod-data/
      - name: Generate audio
        working-directory: main
        run: |
          uv run edge-tts --file $RUNNER_TEMP/articlepod-data/script.txt -v "en-GB-ThomasNeural" --write-media $RUNNER_TEMP/articlepod-data/output.mp3
          ls $RUNNER_TEMP/articlepod-data/
      - name: Upload audio to R2
        uses: cloudflare/wrangler-action@v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4"
          command: |
            r2 object put --file ${{ runner.temp }}/articlepod-data/output.mp3 --remote "${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}/${{ steps.metadata.outputs.slug }}.mp3"

      - name: Commit episode
        working-directory: episodes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cp $RUNNER_TEMP/articlepod-data/episode.json ${{ steps.metadata.outputs.slug }}.json
          git add ${{ steps.metadata.outputs.slug }}.json
          git commit -m "Add episode ${{ steps.metadata.outputs.title }}"
          git push origin episodes
