name: Test

on:
  push:
    branches:
      - main
    paths:
      - "src/python/**"
      - "baml_src/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".python-version"
      - ".github/workflows/test.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync
      - name: Run linters
        run: |
          uv run black --diff --check src/python
          uv run isort --diff --check src/python
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync
      - name: Genrate BAML client
        run: uv run baml generate
      - name: Run tests
        run: uv run pytest tests
